name: Dependabot Auto-Merger

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Update npm Dependencies after Dependabot package upgrade'
    branches:
      - dependabot/npm_and_yarn/**

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}